.mso www.tmac

.TH FOLLOW 1 "2012 Feb 27"

.SH NAME
follow \(en standalone version of \fBtail(1) -f\fP

.SH SYNPOSIS
\fBfollow\fP FILENAME

.SH DESCRIPTION
\fBfollow\fP is a standalone version of \fBtail(1) -f\fR which also
displays the text that is already contained by the input file.

.SH OPTIONS
.PP
FILENAME
.RS 4
The filename of the file which should be followed.
.RE

.SH BUGS
If you hit upon any bug, please report it to the developers at
.URL "https://github.com/dermesser/follow/issues" "the issue tracker" "."
